version: '3'
services:
  dev:
    image: node:latest
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm install && npm run dev
    ports:
      - 1234:1234
      - 1235:1235
